### ISSUE TITLE
Winston 3.x incompatibility

### ISSUE THREAD

**Issue by eli-darkly** [launchdarkly/node-server-sdk#140]
We have not updated the SDK to work with the most recent major version release of Winston, 3.0. Unfortunately, our `package.json` did not specify a `peerDependency` version constraint, so it will not stop you from trying to use the current Winston.

We intend to fix this, though we do need to maintain backward compatibility with Winston 2.x as well. Watch this issue for updates.

**Comment by duro** [comment]
@eli-darkly what is going on here? I cannot install launch darkly into my project which already was using Winston 3.x.

**Comment by bwoskow-ld** [comment]
Hi duro,

I see that you also filed a request with the LaunchDarkly support team. Let's continue the conversation there. I'll follow up publicly on this issue with an update for anyone else following along once we've resolved your support request.

**Comment by bwoskow-ld** [comment]
...circling back to the public issue...

After further investigation we're unable to verify any SDK incompatibilities with Winston 3.x. 

While the SDK depends on Winston 2.4.1, the only Winston APIs in use by the SDK are common across Winston 2.x and 3.x. As a result, the SDK works fine when passed a properly instantiated logger from either version range.

That said, it is possible to run into issues when constructing a Winston logger (prior to passing it into the LaunchDarkly SDK) because of conflicting transitive dependency versions. The SDK depends on Winston 2.4.1 and many other packages depend on Winston 3.x. Anyone who encounters errors constructing their Winston loggers should add an explicit dependency to their project on Winston for the version they were expecting to use.

I have updated the Node SDK reference guide to reflect this.
