### ISSUE TITLE
deprecated crypto package

### ISSUE THREAD

**Issue by pouyaHobbi** [launchdarkly/node-server-sdk#173]

**Comment by eli-darkly** [comment]
Since this issue has no description, I'm not sure if you're referring to the `node-sha1` package specifically, or the fact that we're using SHA1 at all. To be clear, we do not use SHA1 for authentication at all— just to generate a well-distributed set of large integers for computing percentage rollouts of users.

We have been using a pretty old version of `node-sha1` to do this, but since that package is really just a simple wrapper for Node's `crypto`, we can probably just drop that dependency rather than upgrading it.

**Comment by eli-darkly** [comment]
(Tracked internally as 65523)

**Comment by eli-darkly** [comment]
Removed `node-sha1` in the 5.11.0 release.
