### ISSUE TITLE
Streaming Connection not Timing Out

### ISSUE THREAD

**Issue by fredwes** [launchdarkly/node-server-sdk#198]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
Establishing initial connection to receive streaming events does not appear to timeout so that it can try again. Restarting the server manually to initiate reconnect allows the SDK to connect successfully. You can see from the logs below that the connection was initialized and 3 days later it was still not connected. FYI debug logging for the SDK was enabled during this time, so I would expect to have seen the "Opened LaunchDarkly stream connection" in the logs or some failure/retrying log message.

**To reproduce**
Initialize SDK for streaming connection (with proxy). Intermittent issue.

**Expected behavior**
If initial connection cannot be established within some timeout interval then close the connection and try again.

**Logs**
2020-09-18T19:14:00Z "Initializing stream processor to receive feature flag updates"
2020-09-21T14:51:26Z "Variation called before LaunchDarkly client initialization completed (did you wait for the 'ready' event?) - using default value"

**SDK version**
5.13.1

**Language version, developer tools**
nodejs v12.14.0

**OS/platform**
Ubuntu 18.04

**Additional context**

**Comment by eli-darkly** [comment]
Hi. As the text under "Is this a support request?" in the issue template suggests, it might be better to direct this question to the support team - especially since it's an intermittent network-related issue that might depend on some details of your runtime environment rather than only on the SDK code. All I can say from the point of view of the SDK team is that it would be extremely odd for the SDK not to log _anything_ related to connection attempts, and there are only two log lines shown here - both of which are INFO level, so if you did enable DEBUG level it's unclear what if any debug logging appeared. So whatever is going on, I don't think it is as simple as "it didn't have a timeout."

**Comment by fredwes** [comment]
Thanks @eli-darkly, will raise with support
