### ISSUE TITLE
add user variation to feature flag

### ISSUE THREAD

**Issue by finalight** [launchdarkly/node-server-sdk#243]
i know that there's a REST API to allow adding of user target to a feature flag, but is there a nodeJS SDK to do the same?

**Comment by bwoskow-ld** [comment]
Hi @finalight,

Yes, we offer client libraries for utilizing LaunchDarkly's REST API. Take a look [here](https://github.com/search?q=topic%3Alaunchdarkly-api+org%3Alaunchdarkly&type=Repositories) - there's one in JavaScript and another in TypeScript.

These client libraries are separate from our LaunchDarkly SDKs because the SDKs are meant for feature flagging within an application whereas the client libraries are for more general purpose flag/account management as exposed by our REST API.

Cheers,
@bwoskow-ld
