### ISSUE TITLE
Stateless connection approach for feature flags

### ISSUE THREAD

**Issue by milkchocolate** [launchdarkly/node-server-sdk#253]
Hi team, I'm using LaunchDarkly for my projects, it's awesome. I have some questions about how the client connects to the server.

Why is the connection stateful? It adds complexities for using the sdk client. Is it possible to use stateless connection for reading feature flags from the server.

For a stateless connection approach, can I initialize the client just before I read a feature flag and then shut down the client right after I finish the reading? 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/5474821/175209420-5ef2ccc8-c5c1-41ff-b924-4e589a044b61.png">

https://docs.launchdarkly.com/sdk/server-side/node-js#getting-started
Screenshot from the doc:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/5474821/175207136-1ad281a8-0009-4a19-b1da-b3e05043ae54.png">

**Comment by eli-darkly** [comment]
If you haven't seen our docs page on [client-side and server-side SDKs](https://docs.launchdarkly.com/sdk/concepts/client-side-server-side), that might help to clarify things. Like all of the server-side LaunchDarkly SDKs, the server-side Node SDK is designed mainly for use in a long-running application that will need to evaluate feature flags frequently for many different users. In such a context, it's highly desirable to _not_ have to make a new network request just to evaluate one flag. Instead, the SDK downloads the full flag configuration data first and holds it internally, so that when you request flag values for various users, the flags can be evaluated entirely within the SDK. And since flag configurations can be changed at any time, it's also desirable to maintain a streaming connection so that changes can be pushed from LaunchDarkly to the SDK if and when they occur, rather than requiring lots of polling requests to find out if anything has changed.

I don't know the details of your use case, but if what I've said doesn't seem applicable, it might be that what you really want is the client-side Node SDK rather than the server-side one.

**Comment by milkchocolate** [comment]
Hi @eli-darkly, thanks for your reply 👍
